### ISSUE TITLE
USB live disk failed to start

### ISSUE THREAD

**Issue by water4u99** [nchevsky/systemrescue-zfs#11]
Hi, I burn the iso file to usb using rufus. In UIEF/grub i designated to boot with copytoram. The got error msg:

ERROR: '/dev/disk/by-label/SystemResuce+ZFS_7.01_2.0.0' device did not show up after 30 seconds...

When I ls the /dev/disk/by-label/ directory - the file is named SYSTEMRESCU - which is the 11 char windows drive name.  Rufus added the full name in the autorun.inf using the Label option.

I modified the Label in autorun.inf to SYSTEMRESCU, but it errored out with the same message.

Thank you!

**Comment by thebitllc** [comment]
Same problem, but you need to edit the different file:

/boot/grub/grubsrcd.cfg

**Comment by nchevsky** [comment]
Sorry for the very long delay! When using Rufus, select _'Write in DD Image mode'_—not _'ISO Image mode'_—when prompted:

![image](https://github.com/nchevsky/systemrescue-zfs/assets/3987849/e748bbbd-beec-4f0e-91cf-d80b3fc1901d)

You'll then have no problem and be able to boot with default options—no need for `copytoram` or hacking the volume label.
