### ISSUE TITLE
update to 10.02

### ISSUE THREAD

**Issue by ascendbeing** [nchevsky/systemrescue-zfs#12]
10.02 is out now. perhaps you will update to it? it doesn't look like there would be anything necessarily conflicting, cause they just packaged 2 more softwares, no other changes. thanks.

**Comment by rightaditya** [comment]
Updating ZFS would be handy as well, in case one has pools that use features that requires v2.2.x.

**Comment by sandreas** [comment]
> Updating ZFS would be handy as well, in case one has pools that use features that requires v2.2.x.

@ascendbeing 
There also is a [silent data coruption bug ](https://news.ycombinator.com/item?id=38553008) that I would love to see fixed...

**Comment by nchevsky** [comment]
Given how few minor changes there are in 10.02, I'll be skipping that version and building a release once [10.03](https://gitlab.com/systemrescue/systemrescue-sources/-/blob/main/ChangeLog) is out.

**Comment by rugubara** [comment]
I'd vote for OpenZFS 2.2 at the soonest - I need to rescue my server that has 2.2 feature flag in the pool...

**Comment by nchevsky** [comment]
Seeing how v10.03 still has no release date, I've gone ahead and built a release of [SystemRescue v10.02 with ZFS v2.2.2](https://github.com/nchevsky/systemrescue-zfs/releases/tag/v10.02%2B2.2.2). Enjoy!
