### ISSUE TITLE
How to enable openssh server by default?

### ISSUE THREAD

**Issue by razum2um** [nchevsky/systemrescue-zfs#14]
For some reason after booting by usb keyboard is disabled (but I can change boot records). I cannot open terminal and start systemctl services etc (not even ctrl-alt-f*)

Ideally I would like to ssh into the booted systemrescue instance, is it possible to start openssh from boot entries?

**Comment by nchevsky** [comment]
The SSH server _is_ enabled by default (check `systemctl status sshd`), but the stock `iptables` configuration blocks inbound connections. Could you check if the [upstream SystemRescue v10](https://sourceforge.net/projects/systemrescuecd/files/sysresccd-x86/10.02/) has the same keyboard problem and, if so, report it [here](https://gitlab.com/systemrescue/systemrescue-sources/-/issues)?
