### ISSUE TITLE
Current ISO does not fit into a 1G USB stick

### ISSUE THREAD

**Issue by allentiak** [nchevsky/systemrescue-zfs#15]
Hi,
According to my system, my USB stick has a capacity of 956 MB (or MiB?).
However, the image you provide is 988 MB (or MiB?).

When writing the image to the USB stick, `dd` complains that there is not sufficient free space.
Would you be so kind as to please consider making the image just a little bit smaller, so it still fits into a 1G USB stick?

**Comment by nchevsky** [comment]
@allentiak [v11.02+2.2.6](https://github.com/nchevsky/systemrescue-zfs/releases/tag/v11.02%2B2.2.6) is out now, with an ISO image size of 950 MiB. 🎉 Thanks for your suggestion!

**Comment by allentiak** [comment]
Thanks, @nchevsky !
The ISO size is now around 44 MB smaller than my USB stick.
