### ISSUE TITLE
Can we get a release before the new year pls?

### ISSUE THREAD

**Issue by kneutron** [nchevsky/systemrescue-zfs#16]
Latest SR-Z release is still on zfs 2.2.2 and current is 2.2.6... This would help ppl trying to recover Proxmox, among other things ;-)

**Comment by nchevsky** [comment]
@kneutron I'll start working on an update soon. Thanks so much for the sponsorship! 🙌🏻

**Comment by nchevsky** [comment]
@kneutron [v11.02+2.2.6](https://github.com/nchevsky/systemrescue-zfs/releases/tag/v11.02%2B2.2.6) is out now. 🚀 Thanks for your patience!
