### ISSUE TITLE
ERROR: Profile 'init' does not exist!

### ISSUE THREAD

**Issue by Quoor8ee** [nchevsky/systemrescue-zfs#7]
I don't know if this is a bug in mkarchiso or systemresuce-zfs. I consistently get the error 
```
[mkarchiso] ERROR: Profile '/path/to/systemrescue-zfs/init' does not exist!
```
when running `sudo ./build.sh -v`. Running within `bash -x` reveals the problem is within the `setarch x86_64 mkarchiso -v -w work/x86_64 -C work/pacman.conf -D sysresccd init` command of the `make_basefs` routine. Apparently, mkarchiso tries to interpret the `init` part at the end of this command as a profile directory. From what mkarchiso is intended to be good for, this sounds fine, but it obviously is not what the Systemrescue build script environment expects from it.

Where is the archiso profile directory supposed to come from?

**Comment by nchevsky** [comment]
Hi and sorry about the delay!

I believe you may be using a newer version of `archiso` that no longer supports older commands used by SystemRescue's ancient build script. SystemRescue expects [version 43](https://archive.archlinux.org/packages/a/archiso/archiso-43-2-any.pkg.tar.zst) with [these patches](https://github.com/nchevsky/systemrescue-zfs/tree/master/patches) applied.

Could you try again with a downgraded `archiso` package and report back?

**Comment by nchevsky** [comment]
Closing due to lack of response.

**Comment by Ronchou** [comment]
> You're probably using a newer version of `archiso` that no longer supports profiles used by SystemRescue's ancient build script. SystemRescue expects [version 43](https://archive.archlinux.org/packages/a/archiso/archiso-43-2-any.pkg.tar.zst) with [these patches](https://github.com/nchevsky/systemrescue-zfs/tree/master/patches) applied.
> 
> Could you try again with a downgraded—and patched—`archiso` package and report back?

Met the same issue and this fixed for me, thanks!
